name: text-env
channels:
  - conda-forge

dependencies:
  - python=3.11.9
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.7.0
  - pandas=2.2.2
  - nltk=3.8.1
  - autocorrect=2.6.1
  - spacy=3.7.3
  - tqdm=4.66.4
  - numpy=1.26.4
  - scipy=1.13.0
  - matplotlib=3.8.4
  - networkx=3.3
  - rise=5.7.1